---
substitutions:
  device_name: gasmeter

esp8266:
  board: d1_mini_pro
  framework:
    version: recommended

esphome:
  name: ${device_name}
  project:
    name: breaveheard.gasmeter
    version: "2.6"

wifi:
  ap:
    ssid: "Gas-Meter Fallback Hotspot"
    password: "12345678"  # Required in newer versions for security

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
    
ota:
  platform: esphome

improv_serial:

web_server:
  port: 80
  
dashboard_import:
  package_import_url: github://Breaveheard/esphome-gasmeter/gasmeter.yaml@main
  import_full_config: true

debug:

text_sensor:
  - platform: version
    name: "Gas-Meter ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "Gas-Meter IP"
      entity_category: diagnostic
    ssid:
      name: "Gas-Meter SSID"
      entity_category: diagnostic
    bssid:
      name: "Gas-Meter BSSID"
      entity_category: diagnostic
globals:
  - id: total_pulses
    type: int
    initial_value: '0'  # startet mit 0
    restore_value: true
  - id: imp_ratio
    type: float
    initial_value: '0.1'  # vom Gaszaehler
    restore_value: true
  - id: Zustandszahl
    type: float
    initial_value: '0.9645'  # aus der Gasrechnung
    restore_value: true
  - id: Brennwert
    type: float
    initial_value: '10.362'  # aus der Gasrechnung
    restore_value: true  
  - id: initial_consumption
    type: float
    initial_value: '0'  # hier kann der Gaszählerstand initialisiert werden (Faktor 1000 um einen genaueren Wert zu erzeugen)
    restore_value: true
  - id: initial_energy_consumption
    type: float
    initial_value: id(initial_consumption) * id(Brennwert) * id(Zustandszahl) / 1000.0
    restore_value: true

binary_sensor:
  - platform: gpio
    id: internal_pulse_counter
    pin:
      number: GPIO2  # D4 is GPIO2 on ESP8266, using GPIO number is preferred
      mode: INPUT_PULLUP
    name: "Live-Impuls"
    filters:
      - delayed_on: 100ms
    on_press:
      then:
        - lambda: id(total_pulses) += 1;      

  - platform: status
    name: "Status Gas-Meter"
    entity_category: diagnostic

sensor:
  - platform: template
    name: "Gasverbrauch"
    device_class: gas
    update_interval : 10s    
    unit_of_measurement: "m³"
    state_class: total_increasing
    icon: "mdi:fire"
    accuracy_decimals: 2
    lambda: return (id(initial_consumption)/1000.0) + (id(total_pulses) * id(imp_ratio));

  - platform: template
    name: 'Gasverbrauch Energy'
    device_class: energy
    state_class: total_increasing
    update_interval : 10s    
    icon: 'mdi:fire'
    accuracy_decimals: 1
    unit_of_measurement: "kWh"
    lambda: return id(initial_energy_consumption) + (id(total_pulses) * id(imp_ratio) * id(Brennwert) * id(Zustandszahl));
    
  - platform: template
    name: 'Pulse Counter total'
    update_interval : 10s    
    icon: "mdi:counter"
    accuracy_decimals: 0
    unit_of_measurement: "pulses"
    lambda: return id(total_pulses);

